/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cliente_servidor.grafica;

import classes.Cliente;
import classes.Telefone;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harlock
 */
public class Telefones extends javax.swing.JFrame {

    /**
     * Creates new form Telefones
     */
    private Cliente cliente;
    private Cliente clienteNovo;
    private ArrayList<Telefones> telefones;
    private DefaultTableModel tabelaTel;
    public Telefones() {
        initComponents();
        tabelaTel = (DefaultTableModel) tabelaTelefones.getModel();
        clienteNovo = new Cliente();
        
    }
    public void cliente(Cliente cliente){
        this.cliente = cliente;
    }
    private void Listar_Telefones(){
            try {
                if(cliente != null){
                    for (Telefone telefone : cliente.getListaTel()) {
                       tabelaTel.addRow(new Object[]{telefone.getTipo(),telefone.getNumero(), telefone.getId()}); 
                    }
                
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Algo deu errado ao retornar os números de telefone. "+e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTelefones = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnExcluirRow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionarRow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Número", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaTelefones);
        if (tabelaTelefones.getColumnModel().getColumnCount() > 0) {
            tabelaTelefones.getColumnModel().getColumn(2).setMinWidth(0);
            tabelaTelefones.getColumnModel().getColumn(2).setPreferredWidth(0);
            tabelaTelefones.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        btnSalvar.setText("Concluir");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluirRow.setText("Excluir");
        btnExcluirRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirRowActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("Telefone(s)");

        btnAdicionarRow.setText("+");
        btnAdicionarRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluirRow)
                        .addGap(56, 56, 56)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarRow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarRow)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluirRow))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarRowActionPerformed
        try {
            tabelaTel.addRow(new Object[]{"","",""});
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo deu errado ao inserir uma nova linha. "+e);
        }
    }//GEN-LAST:event_btnAdicionarRowActionPerformed

    private void btnExcluirRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirRowActionPerformed
        try {
            int selectLinha = tabelaTelefones.getSelectedRow();
            tabelaTel.removeRow(selectLinha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo deu errado ao excluir a linha. "+e);
        }
    }//GEN-LAST:event_btnExcluirRowActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            ArrayList<Telefone> lista = new ArrayList<Telefone>();
            int i = 0;
            while (true) {                
                Telefone t = new Telefone();
                t.setTipo((String) tabelaTel.getValueAt(i, 1));
                t.setNumero((String) tabelaTel.getValueAt(i, 2));
                if(tabelaTel.getValueAt(i, 3) != null){
                    t.setId((int) tabelaTel.getValueAt(i, 3));
                }
                lista.add(i, t);
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telefones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telefones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarRow;
    private javax.swing.JButton btnExcluirRow;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTelefones;
    // End of variables declaration//GEN-END:variables
}
